<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -h -u -P -k -K -s level1.glb
-->

<script lang="ts" context="module">
	import { Group, Mesh, Quaternion, Vector3 } from 'three';
	import { T, forwardEventHandlers, useTask } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	const load = () => {
		const suspend = useSuspense();
		return suspend(useGltf('models/level1.glb'));
	};

	export const preload = async () => {
		await load();
	};
</script>

<script lang="ts">
	import { AutoColliders, RigidBody } from '@threlte/rapier';
	import { useKeyboardControls } from 'svelte-kbc';
	import type { RigidBody as RigidBodyType } from '@dimforge/rapier3d-compat';

	export const ref = new Group();

	const gltf = load();

	const component = forwardEventHandlers();

	let wall: Mesh, floor: Mesh, wallGroup: Group;
	let wallRigidBody: RigidBodyType, floorRigidBody: RigidBodyType;

	let floorRotation = new Quaternion();
	let floorPosition = new Vector3();
	let wallRotation = new Quaternion();
	let wallPosition = new Vector3();

	const { w, a, s, d, space } = useKeyboardControls();

	useTask((delta) => {
		if ($gltf) {
			if ($w) {
				floor.rotateX((-1 * Math.PI) / 180);
				wallGroup.rotateX((-1 * Math.PI) / 180);
			}
			if ($s) {
				floor.rotateX(Math.PI / 180);
				wallGroup.rotateX(Math.PI / 180);
			}

			floor.getWorldPosition(floorPosition);
			floor.getWorldQuaternion(floorRotation);
			floorRigidBody.setRotation(floorRotation, true);
			floorRigidBody.setTranslation(floorPosition, true);

			wallGroup.getWorldQuaternion(wallRotation);
			wallGroup.getWorldPosition(wallPosition);
			wallRigidBody.setRotation(wallRotation, true);
			wallRigidBody.setTranslation(wallPosition, true);
		}
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Floor">
			<RigidBody type={'fixed'} bind:rigidBody={floorRigidBody}>
				<AutoColliders shape={'convexHull'}>
					<T.Mesh
						name="Cube"
						castShadow
						receiveShadow
						bind:ref={floor}
						geometry={gltf.nodes.Cube.geometry}
						material={gltf.materials.Material}
					/>
					<T.Mesh
						name="Cube_1"
						castShadow
						receiveShadow
						geometry={gltf.nodes.Cube_1.geometry}
						material={gltf.materials.Material}
					/>
				</AutoColliders>
			</RigidBody>
		</T.Group>

		<T.Group name="Wall" bind:ref={wallGroup}>
			<RigidBody type={'fixed'} bind:rigidBody={wallRigidBody}>
				<AutoColliders shape={'trimesh'}>
					<T.Mesh
						name="Wall1"
						castShadow
						receiveShadow
						geometry={gltf.nodes.Wall1.geometry}
						material={gltf.nodes.Wall1.material}
					/>
					<T.Mesh
						name="Wall2"
						castShadow
						receiveShadow
						geometry={gltf.nodes.Wall2.geometry}
						material={gltf.nodes.Wall2.material}
					/>
					<T.Mesh
						name="Wall3"
						castShadow
						receiveShadow
						geometry={gltf.nodes.Wall3.geometry}
						material={gltf.nodes.Wall3.material}
					/>
				</AutoColliders>
			</RigidBody>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
