<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -h -u -P -k -K -s cannon/scene.gltf
Author: luonro11 (https://sketchfab.com/luonro11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cannon-4ca9b1f52fcc4d399ee65ed7778cfe30
Title: Cannon
-->

<script context="module" lang="ts">
	import { Euler, Group } from 'three';
	import { T, forwardEventHandlers, useThrelte } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	import { useKeyboardControls } from 'svelte-kbc';

	const load = () => {
		const suspend = useSuspense();
		return suspend(useGltf('models/cannon/scene.gltf'));
	};

	export const preload = async () => {
		await load();
	};
</script>

<script lang="ts">
	import { useFrame } from '@threlte/core';
	import CannonBall from './CannonBall.svelte';

	type CannonBallProps = {
		power: number;
		rotation: Euler;
	};

	let cannonBalls: CannonBallProps[] = [];

	let power = '100';

	const ref = new Group();
	let cannon: Group;

	const gltf = load();

	const { w, a, s, d, space } = useKeyboardControls();

	useFrame((delta, ctx) => {
		if ($gltf) {
			if ($a) {
				cannon.rotateY((-1 * Math.PI) / 180);
			}
			if ($d) {
				cannon.rotateY(Math.PI / 180);
			}
		}
	});

	const fireCannon = () => {
		cannonBalls = [
			...cannonBalls,
			{
				power: +power,
				rotation: cannon.rotation
			}
		];
	};

	const component = forwardEventHandlers();
</script>

<!-- 
<Pane title="Cannon" position="fixed">
	<Text label="Power" bind:value={power} />
</Pane> -->

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Cannon" bind:ref={cannon}>
			<T.Group rotation={[-Math.PI / 2, 0, 0]}>
				<T.Mesh
					name="Cannon_Model"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Object_2.geometry}
					material={gltf.materials.initialShadingGroup}
					on:click={fireCannon}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />

	{#each cannonBalls as { power, rotation }}
		<CannonBall position={[0, 6, 2]} {power} {rotation} />
	{/each}
</T>
